# Generated by Django 3.2.7 on 2022-04-27 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phome',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.comment'),
        ),
    ]
