# Generated by Django 3.2.7 on 2022-04-27 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220427_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.comment'),
        ),
    ]
