# Generated by Django 3.2.7 on 2022-04-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_bookitem_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='color',
            field=models.CharField(max_length=64),
        ),
    ]
