# Generated by Django 3.2.7 on 2021-12-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner_Platter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=64)),
                ('size_small', models.CharField(max_length=64)),
                ('size_large', models.CharField(max_length=64)),
                ('image', models.ImageField(default=None, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Regular_Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=64)),
                ('size_small', models.CharField(max_length=64)),
                ('size_large', models.CharField(max_length=64)),
                ('toppings', models.IntegerField()),
                ('image', models.ImageField(default=None, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=64)),
                ('image', models.ImageField(default=None, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Sicilian_Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=64)),
                ('size_small', models.CharField(max_length=64)),
                ('size_large', models.CharField(max_length=64)),
                ('toppings', models.IntegerField()),
                ('image', models.ImageField(default=None, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=64)),
                ('size_small', models.CharField(blank=True, max_length=64)),
                ('size_large', models.CharField(max_length=64)),
                ('image', models.ImageField(default=None, upload_to='images')),
                ('extras', models.ManyToManyField(blank=True, to='order.Extra')),
            ],
        ),
    ]
