# Generated by Django 3.2.7 on 2021-12-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
