# Generated by Django 3.2.7 on 2022-05-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20220519_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='color',
            field=models.CharField(max_length=64),
        ),
    ]
